using Microsoft.EntityFrameworkCore;

namespace Restaurant.Api.Data;

public static class SchemaInitializer
{
    public static void EnsureUpdated(RestaurantDbContext db)
    {
        db.Database.ExecuteSqlRaw("""
            CREATE TABLE IF NOT EXISTS "ProductGroups" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" character varying(80) NOT NULL,
                "Description" character varying(240) NOT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProductGroups_Name" ON "ProductGroups" ("Name");

            CREATE TABLE IF NOT EXISTS "ActivityLogs" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Type" character varying(40) NOT NULL,
                "Description" character varying(500) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL
            );

            CREATE INDEX IF NOT EXISTS "IX_ActivityLogs_CreatedAt" ON "ActivityLogs" ("CreatedAt");

            CREATE TABLE IF NOT EXISTS "CashRegisters" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "OpenedAt" timestamp with time zone NOT NULL,
                "ClosedAt" timestamp with time zone NULL,
                "Total" numeric(12,2) NOT NULL DEFAULT 0
            );

            CREATE INDEX IF NOT EXISTS "IX_CashRegisters_OpenedAt" ON "CashRegisters" ("OpenedAt");
            CREATE INDEX IF NOT EXISTS "IX_CashRegisters_ClosedAt" ON "CashRegisters" ("ClosedAt");

            ALTER TABLE "Products"
                ADD COLUMN IF NOT EXISTS "Measure" character varying(40) NOT NULL DEFAULT '';

            ALTER TABLE "Products"
                ADD COLUMN IF NOT EXISTS "ProductGroupId" integer NULL;

            ALTER TABLE "OrderItems"
                ADD COLUMN IF NOT EXISTS "Measure" character varying(40) NOT NULL DEFAULT '';

            ALTER TABLE "Orders"
                ADD COLUMN IF NOT EXISTS "PaidAt" timestamp with time zone NULL;

            ALTER TABLE "Orders"
                ADD COLUMN IF NOT EXISTS "CustomerName" character varying(120) NOT NULL DEFAULT '';

            ALTER TABLE "Orders"
                ADD COLUMN IF NOT EXISTS "CashRegisterId" integer NULL;

            UPDATE "Orders"
            SET "PaidAt" = "CreatedAt"
            WHERE "Status" = 'Paid' AND "PaidAt" IS NULL;

            CREATE INDEX IF NOT EXISTS "IX_Orders_PaidAt" ON "Orders" ("PaidAt");
            CREATE INDEX IF NOT EXISTS "IX_Orders_CashRegisterId" ON "Orders" ("CashRegisterId");

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_Orders_CashRegisters_CashRegisterId'
                ) THEN
                    ALTER TABLE "Orders"
                    ADD CONSTRAINT "FK_Orders_CashRegisters_CashRegisterId"
                    FOREIGN KEY ("CashRegisterId") REFERENCES "CashRegisters" ("Id")
                    ON DELETE SET NULL;
                END IF;
            END $$;

            CREATE INDEX IF NOT EXISTS "IX_Products_ProductGroupId" ON "Products" ("ProductGroupId");

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_Products_ProductGroups_ProductGroupId'
                ) THEN
                    ALTER TABLE "Products"
                    ADD CONSTRAINT "FK_Products_ProductGroups_ProductGroupId"
                    FOREIGN KEY ("ProductGroupId") REFERENCES "ProductGroups" ("Id")
                    ON DELETE SET NULL;
                END IF;
            END $$;
            """);
    }
}
