using Microsoft.EntityFrameworkCore;
using Restaurant.Api.Models;
using Restaurant.Api.Services;

namespace Restaurant.Api.Data;

public static class SchemaInitializer
{
    public static void EnsureUpdated(RestaurantDbContext db, string initialUsername, string initialPassword)
    {
        db.Database.ExecuteSqlRaw("""
            CREATE TABLE IF NOT EXISTS "Users" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Username" character varying(80) NOT NULL,
                "PasswordHash" character varying(256) NOT NULL,
                "PasswordSalt" character varying(128) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Username" ON "Users" ("Username");

            CREATE TABLE IF NOT EXISTS "ProductGroups" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" character varying(80) NOT NULL,
                "Description" character varying(240) NOT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProductGroups_Name" ON "ProductGroups" ("Name");

            CREATE TABLE IF NOT EXISTS "ActivityLogs" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Type" character varying(40) NOT NULL,
                "Description" character varying(500) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL
            );

            CREATE INDEX IF NOT EXISTS "IX_ActivityLogs_CreatedAt" ON "ActivityLogs" ("CreatedAt");

            CREATE TABLE IF NOT EXISTS "CashRegisters" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "OpenedAt" timestamp with time zone NOT NULL,
                "ClosedAt" timestamp with time zone NULL,
                "Total" numeric(12,2) NOT NULL DEFAULT 0
            );

            CREATE INDEX IF NOT EXISTS "IX_CashRegisters_OpenedAt" ON "CashRegisters" ("OpenedAt");
            CREATE INDEX IF NOT EXISTS "IX_CashRegisters_ClosedAt" ON "CashRegisters" ("ClosedAt");

            ALTER TABLE "Products"
                ADD COLUMN IF NOT EXISTS "Measure" character varying(40) NOT NULL DEFAULT '';

            ALTER TABLE "Products"
                ADD COLUMN IF NOT EXISTS "ProductGroupId" integer NULL;

            ALTER TABLE "Products"
                ADD COLUMN IF NOT EXISTS "RequiresStock" boolean NOT NULL DEFAULT true;

            CREATE TABLE IF NOT EXISTS "RawMaterials" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" character varying(120) NOT NULL,
                "Unit" character varying(30) NOT NULL,
                "Quantity" numeric(12,3) NOT NULL DEFAULT 0
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_RawMaterials_Name" ON "RawMaterials" ("Name");

            CREATE TABLE IF NOT EXISTS "ProductIngredients" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ProductId" integer NOT NULL,
                "RawMaterialId" integer NOT NULL,
                "Quantity" numeric(12,3) NOT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProductIngredients_ProductId_RawMaterialId"
                ON "ProductIngredients" ("ProductId", "RawMaterialId");

            CREATE INDEX IF NOT EXISTS "IX_ProductIngredients_RawMaterialId" ON "ProductIngredients" ("RawMaterialId");

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_ProductIngredients_Products_ProductId'
                ) THEN
                    ALTER TABLE "ProductIngredients"
                    ADD CONSTRAINT "FK_ProductIngredients_Products_ProductId"
                    FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id")
                    ON DELETE CASCADE;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_ProductIngredients_RawMaterials_RawMaterialId'
                ) THEN
                    ALTER TABLE "ProductIngredients"
                    ADD CONSTRAINT "FK_ProductIngredients_RawMaterials_RawMaterialId"
                    FOREIGN KEY ("RawMaterialId") REFERENCES "RawMaterials" ("Id")
                    ON DELETE CASCADE;
                END IF;
            END $$;

            ALTER TABLE "OrderItems"
                ADD COLUMN IF NOT EXISTS "Measure" character varying(40) NOT NULL DEFAULT '';

            ALTER TABLE "Orders"
                ADD COLUMN IF NOT EXISTS "PaidAt" timestamp with time zone NULL;

            ALTER TABLE "Orders"
                ADD COLUMN IF NOT EXISTS "CustomerName" character varying(120) NOT NULL DEFAULT '';

            ALTER TABLE "Orders"
                ADD COLUMN IF NOT EXISTS "CashRegisterId" integer NULL;

            UPDATE "Orders"
            SET "PaidAt" = "CreatedAt"
            WHERE "Status" = 'Paid' AND "PaidAt" IS NULL;

            CREATE INDEX IF NOT EXISTS "IX_Orders_PaidAt" ON "Orders" ("PaidAt");
            CREATE INDEX IF NOT EXISTS "IX_Orders_CashRegisterId" ON "Orders" ("CashRegisterId");

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_Orders_CashRegisters_CashRegisterId'
                ) THEN
                    ALTER TABLE "Orders"
                    ADD CONSTRAINT "FK_Orders_CashRegisters_CashRegisterId"
                    FOREIGN KEY ("CashRegisterId") REFERENCES "CashRegisters" ("Id")
                    ON DELETE SET NULL;
                END IF;
            END $$;

            CREATE INDEX IF NOT EXISTS "IX_Products_ProductGroupId" ON "Products" ("ProductGroupId");

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_Products_ProductGroups_ProductGroupId'
                ) THEN
                    ALTER TABLE "Products"
                    ADD CONSTRAINT "FK_Products_ProductGroups_ProductGroupId"
                    FOREIGN KEY ("ProductGroupId") REFERENCES "ProductGroups" ("Id")
                    ON DELETE SET NULL;
                END IF;
            END $$;
            """);

        EnsureInitialUser(db, initialUsername, initialPassword);
    }

    private static void EnsureInitialUser(RestaurantDbContext db, string initialUsername, string initialPassword)
    {
        var existingInitialUser = db.Users.SingleOrDefault(user => user.Username == initialUsername);
        if (existingInitialUser is not null)
        {
            if (PasswordHasher.Verify("admin", existingInitialUser.PasswordHash, existingInitialUser.PasswordSalt))
            {
                var (updatedHash, updatedSalt) = PasswordHasher.HashPassword(initialPassword);
                existingInitialUser.PasswordHash = updatedHash;
                existingInitialUser.PasswordSalt = updatedSalt;
                db.SaveChanges();
            }

            return;
        }

        if (db.Users.Any())
        {
            return;
        }

        var (hash, salt) = PasswordHasher.HashPassword(initialPassword);
        db.Users.Add(new User
        {
            Username = initialUsername,
            PasswordHash = hash,
            PasswordSalt = salt,
            CreatedAt = DateTime.UtcNow
        });
        db.SaveChanges();
    }
}
