using Microsoft.EntityFrameworkCore;

namespace Restaurant.Api.Data;

public static class SchemaInitializer
{
    public static void EnsureUpdated(RestaurantDbContext db)
    {
        db.Database.ExecuteSqlRaw("""
            CREATE TABLE IF NOT EXISTS "ProductGroups" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" character varying(80) NOT NULL,
                "Description" character varying(240) NOT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProductGroups_Name" ON "ProductGroups" ("Name");

            CREATE TABLE IF NOT EXISTS "ActivityLogs" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Type" character varying(40) NOT NULL,
                "Description" character varying(500) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL
            );

            CREATE INDEX IF NOT EXISTS "IX_ActivityLogs_CreatedAt" ON "ActivityLogs" ("CreatedAt");

            ALTER TABLE "Products"
                ADD COLUMN IF NOT EXISTS "Measure" character varying(40) NOT NULL DEFAULT '';

            ALTER TABLE "Products"
                ADD COLUMN IF NOT EXISTS "ProductGroupId" integer NULL;

            ALTER TABLE "OrderItems"
                ADD COLUMN IF NOT EXISTS "Measure" character varying(40) NOT NULL DEFAULT '';

            CREATE INDEX IF NOT EXISTS "IX_Products_ProductGroupId" ON "Products" ("ProductGroupId");

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_Products_ProductGroups_ProductGroupId'
                ) THEN
                    ALTER TABLE "Products"
                    ADD CONSTRAINT "FK_Products_ProductGroups_ProductGroupId"
                    FOREIGN KEY ("ProductGroupId") REFERENCES "ProductGroups" ("Id")
                    ON DELETE SET NULL;
                END IF;
            END $$;
            """);
    }
}
